databases:
  - name: teloapp-db
    plan: free

services:
  - type: web
    name: teloapp-backend
    plan: free
    runtime: docker      # <--- CAMBIO CLAVE
    dockerfilePath: ./teloapp-backend/Dockerfile # <--- CAMBIO CLAVE
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: teloapp-db
          property: connectionString # <-- Nombre corregido
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update