databases:
  - name: teloapp-db
    plan: free

services:
  - type: web
    name: teloapp-backend
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile # <--- CAMBIO CLAVE
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: teloapp-db
          property: connectionString
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update